apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-term-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legal-api
  template:
    metadata:
      labels:
        app: legal-api
    spec:
      containers:
      - name: legal-api
        image: shaizah56/legal-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "1Gi"  # Set memory limit to 1 gigabyte
            cpu: "0.5"     # Set CPU limit to 0.5 cores
          requests:
            memory: "512Mi"  # Set memory request to 512 megabytes
            cpu: "0.1"       # Set CPU request to 0.1 cores

---
apiVersion: v1
kind: Service
metadata:
  name: legal-api-service
spec:
  type: LoadBalancer
  selector:
    app: legal-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
