apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-term-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legal-api
  template:
    metadata:
      labels:
        app: legal-api
    spec:
      containers:
      - name: legal-api
        image: shaizah56/legal-api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: legal-api-service
spec:
  type: LoadBalancer
  selector:
    app: legal-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
