apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-term-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legal-api
  template:
    metadata:
      labels:
        app: legal-api
    spec:
      containers:
      - name: legal-api
        image: IMAGE_NAME_PLACEHOLDER:TAG_PLACEHOLDER
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
